name: Build

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: electronuserland/builder:wine
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: make
